spring.application.name=FarmersDashboard
# MongoDB configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=dashboarddb
testrail.base-url=https://zinnia.testrail.io
testrail.username=Dhruv.Sagar@zinnia.com
testrail.token=YFicLnuOXaHkJ5mBje7c-Xla2m5DW7NXUjcSx2l4C
